name: GitHub Pages Auto-Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy GitHub Page
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm install
    - run: npm run deploy
